### ISSUE TITLE
Backup extensions installers (~ 27 GB)

### ISSUE THREAD

**Issue by Symbian9** [JustOff/ca-archive#8] opened 2018-08-22 00:18 UTC
Currently `master` branch include only catalog, but there NO any archived `*.xpi`.

Is it possible also backup all `*.xpi` packages? It's look like total size of all extensions should be ~ 27 GB.

### NOTE

**Only 2 weeks left** before AMO will remove all `*.xpi`(XUL) extension packages!

- https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/

Deadline: **October 1, 2018** 

> NOTE: After September 5, 2018 submission of updated add-ons to official AMO dissabled!

**Comment by JustOff** [comment] 2018-08-22 12:54
Thanks, I'm aware of this; the first mirror is already created and is in the testing state.

**Comment by Bfgeshka** [comment] 2018-08-22 13:16
I wonder if addon collection can be uploaded to archive.org, those guys are pretty good at preserving.

**Comment by JustOff** [comment] 2018-08-22 14:31
@Bfgeshka, it's not so simple, but I have some idea I'm going to try when we have the mirror up and running.

**Comment by Tallefer** [comment] 2018-08-22 19:01
Wow, archive.org is (potentially) an excellent option! @Bfgeshka , thanks for suggestion!
In the first days of this repo, I was thinking about posting a long detailed list of different possible options, primarily about storage organizing, and also about distribution schemes. But then my hardware had failed me. -_-
Still, the timer is ticking and I should ask: @JustOff , what do you think about making a torrent? Apart from using Archive.org (probably the best option as a second mirror) this is the most reliable storage option for such a task IMO.

**Comment by krisu5** [comment] 2018-08-23 14:48
@Tallefer After uploading files to Archive.org, it creates torrent automatically.

**Comment by tyaremco** [comment] 2018-08-30 03:55
@JustOff does the mirror contain installers for all versions of an addon, or just the most recent?

**Comment by JustOff** [comment] 2018-08-30 09:15
@tyaremco, it will have all versions currently listed in ca-archive.

**Comment by sda2b** [comment] 2018-09-07 02:53
Hello,

What's the current situation for this ? I backed up the ones I was using but I'd like to know if you guys sorted it out. (aka Archive Everything !!)

Thanks

**Comment by JustOff** [comment] 2018-09-07 13:09
Everything will happen in due time.

**Comment by grahamperrin** [comment] 2018-09-16 17:55
> Deadline: September 5, 2018

That was for submissions for new legacy add-on versions. 

From the blog post: 

>> All legacy add-on versions will be disabled in early October, 2018.

**Comment by Symbian9** [comment] 2018-09-16 20:51
> That was for submissions for new legacy add-on versions.

OK. Header of this issue updated:

> Deadline: October 1, 2018

**Comment by Symbian9** [comment] 2018-09-30 15:30
> Deadline: October 1, 2018

October 1 coming in 1 day. Any news, @JustOff?

**Comment by grahamperrin** [comment] 2018-09-30 16:18
Early October, not necessarily tomorrow. The issue is not yet mile-stoned, keep an eye on these three: 

- https://github.com/mozilla/addons-server/milestone/129
- https://github.com/mozilla/addons-server/milestone/130
- https://github.com/mozilla/addons-server/milestone/131

Generally, for the legacy front end: 

- https://github.com/mozilla/addons-server/labels/component%3A%20legacy%20frontend

**Comment by JustOff** [comment] 2018-10-06 21:33
Resolved by [CAA 1.2.0](https://github.com/JustOff/ca-archive/releases/tag/1.2.0).

**Closed by JustOff** 2018-10-06 21:33 UTC
