### ISSUE TITLE
An problem

### ISSUE THREAD

**Issue by mini536** [JustOff/ca-archive#79] opened 2020-04-14 14:28 UTC
I want to make a mirror site of this website, can you tell me how should I start?

**Comment by JustOff** [comment] 2020-04-14 15:36
Duplicate of #39.

**Closed by JustOff** 2020-04-14 15:36 UTC

**Comment by mini536** [comment] 2020-04-15 07:35
> 
> 
> Duplicate of #39.

Well,I don't think I can't download all the files on my server,because my server have 250GB left.
