### ISSUE TITLE
Tray icon forces status bar to always open on launch

### ISSUE THREAD

**Issue by TiberiumFusion** [JustOff/ca-archive#88] opened 2020-11-25 01:51 UTC
If I put the CA Archive addon's tray icon in the status bar, it will force the status bar to always open when the browser starts.

Example situation:
1. Put addon tray icon in the status bar.
2. Hide the status bar.
3. Relaunch the browser.
4. Notice the status bar is open (should be hidden).
5. Hide the status bar again.
6. Relaunch the browser.
7. Notice the status bar is open.
Etc etc etc

I've never seen an addon do this before.
For someone who likes to use the status bar as a toggleable, quick access to addons only when I need them, this is rather annoying. I have to manually close the status bar every time I launch my browser or place the CA Archive's tray icon in an obtrusive location that is always visible (e.g. URL bar).

Tested on Firefox ESR 52.9.0 and Basilisk 2020.10.18

**Comment by JustOff** [comment] 2020-11-25 10:42
Duplicate of #70.

**Closed by JustOff** 2020-11-25 10:42 UTC

**Comment by TiberiumFusion** [comment] 2020-11-25 21:37
@JustOff
Setting `extensions.ca-archive.unhideToolbar` to false did indeed resolve the issue. Thank you.
Fwiw, this is extremely rare behavior for an addon, and it would be much more conventional for this property to default to false instead of true.
